import { cookies } from "next/headers";
import Header from "./components/Header";
import "./globals.css";
import { COLOR_MODE } from "@/app/utils/types";
import ThemeProvider from "./context/ThemeContext";
import ThemeSwitcher from "./components/ThemeSwitcher";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const appCookies = cookies();
  const colorMode = appCookies.get("color_mode")?.value;

  return (
    <html lang="en">
      <body>
        <ThemeProvider
          initialValue={{
            color:
              colorMode === COLOR_MODE.DARK
                ? COLOR_MODE.DARK
                : COLOR_MODE.LIGHT,
          }}
        >
          <Header title="Where in the world?">
            <ThemeSwitcher />
          </Header>
          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
